=== Daaniel-Sans/xml_dtd_prueba/Exercise2/sales_rules.dtd
<!ELEMENT sales_record (date, customer, items)>
<!ATTLIST sales_record record_id ID #REQUIRED>

<!ELEMENT date (#PCDATA)>

<!ELEMENT customer (customer_name, email)>
<!ELEMENT customer_name (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT items (item+)>
<!ELEMENT item (item_name, quantity, price)>

<!ELEMENT item_name (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price currency CDATA "EUR">

=== Daaniel-Sans/xml_dtd_prueba/Exercise2/external_record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sales_record SYSTEM "sales_rules.dtd">
<sales_record record_id="SR002">
    <date>2026-02-11</date>
    <customer>
        <customer_name>Paco Ruiz</customer_name>
        <email>paco_r@email.com</email>
    </customer>
    <items>
        <item>
            <item_name>Acoustic Guitar Strings</item_name>
            <quantity>3</quantity>
            <price>12.00</price>
        </item>
    </items>
</sales_record>

=== Daaniel-Sans/xml_dtd_prueba/Exercise2/mixed_record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sales_record SYSTEM "sales_rules.dtd" [
    <!ENTITY store_name "Tech Central Station">
]>
<sales_record record_id="SR003">
    <date>2026-02-12</date>
    <customer>
        <<customer_name>Benito PÃ©rez</customer_name>
        <email>benito_p@email.com</email>
    </customer>
    <items>
        <item>
            <item_name>Wireless Mouse</item_name>
            <quantity>1</quantity>
            <price currency="EUR">25.00</price>
        </item>
    </items>
</sales_record>
